config/routes.rb
Rails.application.routes.draw do
  resources :questionnaires
  root 'questionnaires#index'
end

app/models/numeric_question.rb
class NumericQuestion < Question
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :questionnaire

  def self.types
    [NumericQuestion, TextQuestion]
  end
end

app/models/questionnaire.rb
class Questionnaire < ActiveRecord::Base

  has_many :questions

  accepts_nested_attributes_for :questions

end

app/models/text_question.rb
class TextQuestion < Question
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  before_action :set_questionnaire, only: [:show, :edit, :update, :destroy]

  # GET /questionnaires
  # GET /questionnaires.json
  def index
    @questionnaires = Questionnaire.all
  end

  # GET /questionnaires/1
  # GET /questionnaires/1.json
  def show
  end

  # GET /questionnaires/new
  def new
    @questionnaire = Questionnaire.new
  end

  # GET /questionnaires/1/edit
  def edit
  end

  # POST /questionnaires
  # POST /questionnaires.json
  def create
    @questionnaire = Questionnaire.new(questionnaire_params)

    respond_to do |format|
      if @questionnaire.save
        format.html { redirect_to @questionnaire, notice: 'Questionnaire was successfully created.' }
        format.json { render :show, status: :created, location: @questionnaire }
      else
        format.html { render :new }
        format.json { render json: @questionnaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questionnaires/1
  # PATCH/PUT /questionnaires/1.json
  def update
    respond_to do |format|
      if @questionnaire.update(questionnaire_params)
        format.html { redirect_to @questionnaire, notice: 'Questionnaire was successfully updated.' }
        format.json { render :show, status: :ok, location: @questionnaire }
      else
        format.html { render :edit }
        format.json { render json: @questionnaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questionnaires/1
  # DELETE /questionnaires/1.json
  def destroy
    @questionnaire.destroy
    respond_to do |format|
      format.html { redirect_to questionnaires_url, notice: 'Questionnaire was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_questionnaire
      @questionnaire = Questionnaire.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def questionnaire_params
      params.require(:questionnaire).permit(:title, :description, questions_attributes: [:id, :type, :text, :max])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questionnaires_helper.rb
module QuestionnairesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JedijsSpike</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questionnaires/_form.html.erb
<%= form_for(@questionnaire, builder: KoFormBuilder, html: { class: 'ko-form' },
      data: { model: @questionnaire.to_json(include: {questions: {methods: :type}}), viewmodel: 'Questionnaire' }) do |f| %>

  <% if @questionnaire.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@questionnaire.errors.count, "error") %> prohibited this questionnaire from being saved:</h2>

      <ul>
      <% @questionnaire.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>

  <div>
    <%= f.fields_for :questions do |g| %>
      <hr/>
      <h3>Question</h3>
      <%= g.hidden_field :id %>
      <div class="field">
        <%= g.label :text %><br>
        <%= g.text_field :text %>
      </div>
      <div class="field">
        <%= g.label :type %><br>
        <%= g.select :type, options_for_select(Question.types.map{|t| [t.to_s.titleize, t]}) %>
      </div>
      <div class="field" data-bind="visible: isNumeric">
        <%= g.label :max %><br>
        <%= g.number_field :max %>
      </div>
      <%= f.action 'Alert question', 'say' %>
    <% end %>
    <hr/>
    <%= f.add_item :questions, label: "Add new question", viewmodel: 'Question' %>
  </div>

  <%= f.action 'Alert questionnaire', 'say' %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questionnaires/edit.html.erb
<h1>Editing questionnaire</h1>

<%= render 'form' %>

<%= link_to 'Show', @questionnaire %> |
<%= link_to 'Back', questionnaires_path %>

app/views/questionnaires/index.html.erb
<h1>Listing questionnaires</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questionnaires.each do |questionnaire| %>
      <tr>
        <td><%= questionnaire.title %></td>
        <td><%= questionnaire.description %></td>
        <td><%= link_to 'Show', questionnaire %></td>
        <td><%= link_to 'Edit', edit_questionnaire_path(questionnaire) %></td>
        <td><%= link_to 'Destroy', questionnaire, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Questionnaire', new_questionnaire_path %>

app/views/questionnaires/new.html.erb
<h1>New questionnaire</h1>

<%= render 'form' %>

<%= link_to 'Back', questionnaires_path %>

app/views/questionnaires/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @questionnaire.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @questionnaire.description %>
</p>

<%= link_to 'Edit', edit_questionnaire_path(@questionnaire) %> |
<%= link_to 'Back', questionnaires_path %>